services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ../wppconnect-data:/data
    ports:
      - '8080:21465'
